### ISSUE TITLE
Many errors after update

### ISSUE THREAD

**Issue by NeboutL** [NuCivic/dkan#1840] opened 2017-04-06 06:28 UTC
Hello everybody ,
After performed an update ( Module -> Update -> Check manually)
I have several  errors : 

Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 201 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 241 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Failed to get available update data for 3 projects.
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 201 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 216 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 241 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: project_type in update_manager_update_form() (line 112 of /var/www/html/dkan/modules/update/update.manager.inc).
Notice: Undefined index: project_type in update_manager_update_form() (line 112 of /var/www/html/dkan/modules/update/update.manager.inc).

I installed dkan-drops-7-master and I updated the version with dkan-7.x-1.13.2.
Thanks for your help , 
Best regards, 
Laurent

**Comment by odvietnam** [comment] 2017-04-06 12:42
We had the same issue. In addition, our site cannot view datasets anymore. Error returns:

> EntityMetadataWrapperException: Unknown data property field_modified_source_date. in EntityStructureWrapper->getPropertyInfo() (line 354 of ...dkan/modules/contrib/entity/includes/entity.wrapper.inc).

**Comment by mohnjatthews** [comment] 2017-04-06 12:48
This error seems to be effecting (*affecting?*) a lot of users. A similar bug was mentioned #1759 the other day. I'm currently half way through building DKAN from the latest branch, hopefully that won't have these errors in. I'll post back here when I've got an answer.

**Comment by janette** [comment] 2017-04-06 13:02
The errors related to dkan_sitewide_update_status_alter() do not affect the functionality of DKAN, a fix for those will be in the next patch release (7.x-1.13.3), see #1804.

1.13 is a major upgrade, please take note of the [release notes](https://github.com/NuCivic/dkan/releases/tag/7.x-1.13) that list the extra steps to run to get everything in order. If you still see errors after running the db update and feature revert commands please send us specific details of your build and the errors you see so we can try to reproduce them.

**Comment by NeboutL** [comment] 2017-04-07 00:41
Hi Everyody , 
Thanks for all comments.
I updated all files indicate on this link. That's work good !!!
[https://github.com/NuCivic/dkan/pull/1804](url)
皆本当にありがとうございました＾＿＾

**Comment by dafeder** [comment] 2017-04-10 13:17
@odvietnam did you run update.php after updating your code? What version are you running right now? See the [release notes for 1.13.3](https://github.com/NuCivic/dkan/blob/1.13.3/docs/releases/notes/1.13.3.rst), (which still does not have an official release)

**Comment by odvietnam** [comment] 2017-04-11 09:42
Thanks @dafeder  We are using Dkan 7.x-1.13 with latest Drupal 7. We did run update.php. We did not have Drush before installing Drupal and Dkan though. I guess some of the necessary Drush commands cannot be done via regular web-based admin?

**Comment by odvietnam** [comment] 2017-04-23 08:25
> Notice: Undefined index: bundle in FeedsProcessor->bundle() .... /dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).

This still happens in the latest release of DKAN. Quite annoying.

**Comment by mohnjatthews** [comment] 2017-04-25 08:39
Can confirm that I am also still getting the error:

```
Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /vagrant/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).
Unable to send e-mail. Contact the site administrator if the problem persists.
```
I noticed that it only showed up once I updated the Feeds module. I'll try downgrading it to see if the update was the problem.

**Comment by mohnjatthews** [comment] 2017-04-25 08:46
I rolled back and I'm currently running `Feeds 7.x-2.0-beta1+17-dev` **without any issues**. The latest suggested release is `Feeds 7.x-2.0-beta3`, however I see the `Undefined index` error mentioned above when this version is installed.

@odvietnam, can you check which version you're running?

**Comment by odvietnam** [comment] 2017-04-25 13:35
I updated to the latest (7.x-2.0-beta1+17-dev) but found too many errors so I rolled back. The previous version has no problem.

**Comment by mohnjatthews** [comment] 2017-04-25 14:16
@odvietnam I'm confused. Did you upgrade **to** `7.x-2.0-beta1+17-dev` or upgrade **from** `7.x-2.0-beta1+17-dev` to `Feeds 7.x-2.0-beta3`?

Which Feeds version are you running now?

**Comment by odvietnam** [comment] 2017-04-25 14:45
Sorry for the confusion. I am using 7.x-2.0-beta1+17-dev (comes with latest DKAN Drop 7). The version 7.x-2.0-beta3 caused errors.

**Comment by janette** [comment] 2017-07-11 19:45
Great sounds like all issues have been addressed:
1. `dkan_sitewide_update_status_alter()` errors have been fixed in the 7.x-1.13.3 patch release
2. Running the deployment steps from the release notes clears up other issues: 
```ahoy drush rr
ahoy drush fr dkan_dataset_content_types -y
ahoy drush fr dkan_permissions -y
If ODFE is enabled then: ahoy drush fr open_data_federal_extras -y
If ODFE is enabled then: rm -rf sites/all/modules/open_data_federal_extras
ahoy drush fr open_data_schema_map_dkan -y
ahoy drush updatedb -y
ahoy drush en dkan_ipe -y
ahoy drush en dkan_harvest_dashboard -y
ahoy drush en menu_admin_per_menu -y
ahoy drush fra -y
ahoy drush rr
```
3. And upgrading the feeds module will break your site, stay with the version supplied by the distribution

**Closed by janette** 2017-07-11 19:45 UTC
