### ISSUE TITLE
Remove pager on og_count view

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#819] opened 2015-12-11 22:21 UTC
## Description
The og_count view has the pager settings set to show 10 items and full pager. If a group has more than 10 datasets assigned to it, the /groups page view will display a pager below the dataset count button for that group.

![screenshot_12_11_15__4_07_pm](https://cloud.githubusercontent.com/assets/314172/11756861/812f7602-a022-11e5-950d-3d73787d57e9.png)

![screenshot_12_11_15__4_09_pm](https://cloud.githubusercontent.com/assets/314172/11756867/8691d86a-a022-11e5-8b05-d860de0e2a44.png)

## Steps to Reproduce
1. Spin up a fresh dkan site
2. Use devel to generate 11 or more datasets and assign them all to a single group.
3. Click the 'Groups' link in the main menu
4. Notice that the group with 11 or more datasets has a pager below it

## Acceptance Criteria
When a site admin adds more than 11 datasets to a group, and visits the groups page, they should not see an extra pager below the dataset count button for that group.

**Comment by acouch** [comment] 2016-01-06 20:32
This is a duplicate of https://github.com/NuCivic/dkan/issues/590

**Closed by acouch** 2016-01-06 20:32 UTC
Labels: bug

**Comment by janette** [comment] 2016-01-11 16:35
https://github.com/NuCivic/dkan/issues/590 does not fix this issue
