### ISSUE TITLE
Format of date filters becomes corrupted when filtering datasets

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#993] opened 2016-03-21 17:35 UTC
See; NCS-101 for comments thread

## Description:
Format of date filters becomes corrupted when filtering by tags and format
## Steps to Reproduce:
Instructions to reproduce: Click on Groups, Note the ‘Filter by date changed’ on the left. The dates look just fine. In the ‘Filter by tags’ section, click on the the ‘transportation’ tag. Now look at the ‘Filter by date changed’. The formatting appears to be messed up, the dates should look like they did before. Remove the ‘boundary’ tag and now click on ‘html’ format. The same problem will occur.
This has been confirmed on DKAN 7.x-1.10 and 7.x-1.11.
## Acceptance Criteria
The "Filter by date changed" options for faceted search on Group pages should always look like dates, e.g., "February 4, 2016," not "17:04" or "16:__".
Test Updates
Documentation Updates

**Comment by janette** [comment] 2016-03-21 18:08
duplicate of: https://github.com/NuCivic/dkan/issues/976

**Closed** 2016-03-21 18:09 UTC
Labels: bug
