### ISSUE TITLE
DKAN not show .csv tables

### ISSUE THREAD

**Issue by leogoncalves** [NuCivic/dkan#334] opened 2015-01-20 13:53 UTC
I'm having trouble with viewing .csv files in DKAN. Although the files are in the datastore, the grid view is not displayed. other files, such as xls are displayed smoothly. I checked the settings, checked if the recline view was activated, but everything is as it should. I have no idea what it could be.

**Comment by drkloc** [comment] 2015-01-30 15:50
are you getting js errors or warnings? We have been fixing a lot of those lately.

**Comment by redheadevans** [comment] 2015-01-31 12:54
I am using the 7.27 version. The .csv files are no longer rendered of a sudden. Considered reinstall recline.js module, but other types of files are still rendered.

**Comment by drkloc** [comment] 2015-02-03 03:29
@redheadevans that's the drupal version. Can you take a look at profiles/dkan/CHANGELOG.txt and put the version of dkan that you are running?

Did you update modules in ```profiles/dkan/modules/contrib``` yourself?

**Comment by acouch** [comment] 2015-02-14 14:08
I think this was broken because of a regression from the recline module for linked files. I think this fixed the issue: https://github.com/NuCivic/recline/commit/4b4e470c35cb91d770d84ce9aec82be047c08e80

Can you update your recline module and check?

**Comment by drkloc** [comment] 2015-07-06 18:32
Reopen if this is still an issue. Closing.

**Closed by drkloc** 2015-07-06 18:32 UTC
Labels: component: dkan_dataset, component: recline, Need more context
