### ISSUE TITLE
Comma is missing from the y-axis numbers for visualization

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1066] opened 2016-04-13 19:53 UTC
## Description
The comma is missing from the y-axis numbers for the following visualization - see ncs-281 
I.e. the number 3,350 appears as "3350" instead.  Client states that this is " despite [that formatting] being selected in the format options" but unable to confirm that. When editing the visualization the Y-Axis formatting is currently set to "100,000%". I tried to change the Format to 100,000 (Numbers). I saved my changes but when I refreshed the page the Y Axis Format was still 100,000%"

## Steps to Reproduce
see ncs ticket: NCS-281
Look at the Y Axis labeling and see that it currently does not include commas. 
Click the "Edit" button
Scroll down to "Y Axis" and try to the change the Format from "100,000%" to 100,000 (Numbers). Save your changes and reload the page
You'll see the Y Axis Format is still set to "100,000%"
 
## Documentation Updates

**Comment by jpasila** [comment] 2016-04-13 19:54
per Jacinto: I checked and this bug is a product bug. I did a fresh dkan install and we have the same problem. I checked we lost color value on the preview chart too. We should have the default values used

**Comment by dafeder** [comment] 2016-04-18 16:25
Duplicate of #1063

**Closed by dafeder** 2016-04-18 16:25 UTC
Labels: bug
