### ISSUE TITLE
Cannot reset password after using login link

### ISSUE THREAD

**Issue by poliveiraIPB** [NuCivic/dkan#1464] opened 2016-10-26 11:43 UTC
When using a password reset link, we are redirected to the user's landing page. If we then try to change our password by visiting the account edit page, we are prompted for our old password (which we obviously don't have, or we wouldn't be using a password reset link).

This problem still occurs in:
Drupal 7.41
DKAN (dkan-7.x-1.x)

**Comment by dafeder** [comment] 2016-10-26 14:06
Duplicate of #873

**Closed** 2017-03-27 23:46 UTC
