### ISSUE TITLE
DKAN Trouble

### ISSUE THREAD

**Issue by suhasgr** [NuCivic/dkan#326] opened 2015-01-09 22:59 UTC
Hey While using DKAN module I am facing following problem, Please help

1) When I add dataset and data in DKAN and click on save I end up with blank page and when I go home page I see the following error.

Resource Lakes Locations Near United States has been created.
Your file for this resource is not added to the datastore. Click "Manage Datastore" to import file into the datastore.
Your file for this resource is not added to the datastore. Click "Manage Datastore" to import file into the datastore.

I am unable to find "Manage DataStore" and don't know what to do about it.

**Comment by acouch** [comment] 2015-01-12 20:39
Thank you for reporting your issue.

Can you tells us what operating system and version you are using? Did you receive any messages in the log?

**Comment by suhasgr** [comment] 2015-01-19 07:25
Hi

I am using Windows 7 32 bit

Regards
Suhas

On 12 January 2015 at 15:39, Aaron Couch <notifications@github.com> wrote:

> Thank you for reporting your issue.
>
> Can you tells us what operating system and version you are using? Did you
> receive any messages in the log?
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by suhasgr** [comment] 2015-01-23 20:07
I am following the instructions given as in http://docs.getdkan.com/dkan-documentation/dkan-users/adding-datasets-dkan-0. 

Now there is a problem when I click Additional Info or Save. The same issue as the screen goes blank.

**Comment by acouch** [comment] 2015-01-26 15:39
What version of PHP are you using? Are there any notices from your PHP or Apache logs?

**Comment by suhasgr** [comment] 2015-01-26 15:51
There we no such notices . I will update you with the php version .

**Comment by drkloc** [comment] 2015-01-30 16:20
@suhasgr can you provide a link to the csv file you are using?

**Comment by suhasgr** [comment] 2015-02-03 00:38
Hi

This is the file.

Regards
Suhas

On 30 January 2015 at 11:20, Teofilo Sibileau <notifications@github.com>
wrote:

> @suhasgr <https://github.com/suhasgr> can you provide a link to the csv
> file you are using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NuCivic/dkan/issues/326#issuecomment-72226527>.
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by suhasgr** [comment] 2015-02-03 01:40
Hi

After Disabling the few unwanted modules and extending the memory in the
server, i don't that blank screen anymore.

The dataset loading was completed and I can go to dataset and download it.
But when I click on "explore data"  the following error occur(Attached
Image). After few attempts the error goes off but I am unable to see the
tab of
Grid,Graph and Map.


Regards
Suhas

On 2 February 2015 at 19:38, suhas gr <suhasgrgr@gmail.com> wrote:

> Hi
>
> This is the file.
>
> Regards
> Suhas
>
> On 30 January 2015 at 11:20, Teofilo Sibileau <notifications@github.com>
> wrote:
>
>> @suhasgr <https://github.com/suhasgr> can you provide a link to the csv
>> file you are using?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/NuCivic/dkan/issues/326#issuecomment-72226527>.
>>
>
>
>
> --
> Suhas
>
> *Master's StudentIndiana University*
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by suhasgr** [comment] 2015-02-03 02:50
Hi
Now I enabled DKAN Datastore and facing a issue. I don't know whether it is
related to the previous issue.

I am getting the following Error

Fatal error: Call to undefined function feeds_get_importer_ids() in
/ip/workshop/www/drupal7/sites/all/modules/dkan_datastore/dkan_datastore.module
on line 115


https://github.com/NuCivic/dkan/issues/231
https://github.com/NuCivic/dkan/issues/169

these two links says other people are also facing the same issue.

Can you help?

Regards
Suhas

On 2 February 2015 at 20:40, suhas gr <suhasgrgr@gmail.com> wrote:

> Hi
>
> After Disabling the few unwanted modules and extending the memory in the
> server, i don't that blank screen anymore.
>
> The dataset loading was completed and I can go to dataset and download it.
> But when I click on "explore data"  the following error occur(Attached
> Image). After few attempts the error goes off but I am unable to see the
> tab of
> Grid,Graph and Map.
>
>
> Regards
> Suhas
>
> On 2 February 2015 at 19:38, suhas gr <suhasgrgr@gmail.com> wrote:
>
>> Hi
>>
>> This is the file.
>>
>> Regards
>> Suhas
>>
>> On 30 January 2015 at 11:20, Teofilo Sibileau <notifications@github.com>
>> wrote:
>>
>>> @suhasgr <https://github.com/suhasgr> can you provide a link to the csv
>>> file you are using?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/NuCivic/dkan/issues/326#issuecomment-72226527>.
>>>
>>
>>
>>
>> --
>> Suhas
>>
>> *Master's StudentIndiana University*
>>
>
>
>
> --
> Suhas
>
> *Master's StudentIndiana University*
>



-- 
Suhas

*Master's StudentIndiana University*

**Comment by dafeder** [comment] 2015-02-10 22:09
Suhas - I'm going to close this issue, as it is a duplicate of #169. Any further discussion should happen in that ticket. Thanks!

**Closed by dafeder** 2015-02-10 22:09 UTC
Labels: Need more context
