### ISSUE TITLE
Move dkan_dataset make file into dkan core

### ISSUE THREAD

**Issue by frankcarey** [NuCivic/dkan#510] opened 2015-06-18 00:52 UTC
There are a ton of things in dkan_dataset that are not very specific to dkan_dataset. Things like views, features, panels, etc. I think we should move those dependent modules into dkan proper. 

PR en route

**Comment by janette** [comment] 2017-07-12 20:12
Duplicate of #520 
Several modules were consolidated into core and the make file simplified here #1387

**Closed by janette** 2017-07-12 20:12 UTC
