### ISSUE TITLE
@font-your-face: Font names should not change fonts in preview boxes

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#602] opened 2015-07-29 01:46 UTC
All of the font names are displayed in the font I'm using on my site. They should be displayed in whatever the DKAN default font is.

![screen shot 2015-07-23 at 6 36 14 pm](https://cloud.githubusercontent.com/assets/9059428/8948154/e946bfa0-3571-11e5-8de4-3968d82d4d91.png)

**Comment by kimwdavidson** [comment] 2017-10-20 20:55
Works as intended. If this is reported as a usability issue, we can reassess. Closing

**Closed by kimwdavidson** 2017-10-20 20:55 UTC
Labels: Component: Nuboot_Radix
