### ISSUE TITLE
 Illegal choice error message is displayed when clicking the Next button within a Group

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan#1005] opened 2016-03-21 18:38 UTC
See: NCS-27

## Description:
Illegal choice error message is displayed when clicking the Next button within a Group

Severity: Medium

## Instructions to reproduce: 

Go to https://xyzclient/groups and click on the Game and Fish logo. Scroll down and click on the Next button.

**Comment by acouch** [comment] 2016-04-18 16:18
This is a duplicate of: https://github.com/NuCivic/dkan/issues/912

**Closed** 2016-04-18 16:20 UTC
Labels: bug
