### ISSUE TITLE
Charts Keeps "Forgetting" the X-Format or Y-Format You've Chosen

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan#2096] opened 2017-09-05 19:49 UTC
This is an older issue that I've run into on multiple DKAN sites - it seemed to have been fixed at one point, but I can't find the original ticket.

When you're creating a new Chart in DKAN, if you choose a specific way to format the X or Y axis values (known as X-format and Y-format), the chart should change how the values are presented. 

For example, if I had a population chart where the Y-axis read "1,000; 5,000; 10,000" and I wanted it to be shown as "1K; 5K; 10K" instead, then I would choose the Y-axis format called "100K."

In turn, the chart will change to reflect this -- see screenshot:

![screenshot 2017-09-05 15 45 07](https://user-images.githubusercontent.com/9059428/30080330-3c004eee-9251-11e7-8477-cf6959be3219.png)

The bug on certain DKAN sites is that it keeps "forgetting" the setting you've chosen.

When creating the Population of California chart on one of these sites, if you click "Save," it'll display the chart with "100K, 500K, 1M..." as expected. 

However, if you click "Edit" and change something else (i.e. the chart's colors or margins) and then click Save again, the Chart reverts back to the default X- or Y-format setting.

See below:

![screenshot 2017-09-05 15 48 46](https://user-images.githubusercontent.com/9059428/30080476-b9431e22-9251-11e7-9cad-51eef1cf0905.png)

For this issue to be fixed, Charts must be able to keep track of which options you've chosen.

**Comment by jvitello** [comment] 2017-09-06 15:19
I tried reproducing this, and I think the issue is that the 100,000 formatting doesn't work. You can save a chart with different formats back and forth and they stick, so there doesn't seem to be an issue with retaining the configurations.

This is an old bug from 1.12.x. I created a new ticket with the details. Closing this one:
https://github.com/NuCivic/dkan/issues/2098

**Closed by jvitello** 2017-09-06 15:19 UTC
Labels: bug, Component: Viz Entity
