### ISSUE TITLE
dkan_groups view displays 10 items on a 3 column grid

### ISSUE THREAD

**Issue by janette** [NuCivic/dkan#805] opened 2015-12-07 20:43 UTC
## Description
When a site has more than 10 groups, the pagination settings display 10 groups per page but the view is using a 3 column grid which leaves the last row of the view with a single group. Not pleasing to the eye.

![screenshot_12_7_15__2_35_pm](https://cloud.githubusercontent.com/assets/314172/11639034/ddce8708-9cef-11e5-8f9d-d76c903f4eec.png)

![screenshot_12_7_15__2_40_pm](https://cloud.githubusercontent.com/assets/314172/11639126/7d9eba5a-9cf0-11e5-866b-a548024fa8a1.png)

**The default pager settings should be set to 9 or 12 items per page.**

## Steps to Reproduce
- [ ] Add 11 or more groups to the site
- [ ] Navigate to the groups page
- [ ] Notice that the last row has only one group and to view the 11th group you need to click to the next page

## Acceptance Criteria

When 10 or more groups are added to the site, and you navigate to the Groups page, you should see 9 groups per page.

**Comment by acouch** [comment] 2016-01-06 20:29
This is a duplicate of https://github.com/NuCivic/dkan/issues/741

**Closed by acouch** 2016-01-06 20:29 UTC
